server:
  port: ${PORT}  # Valor por defecto si PORT no está configurado
  url: ${SERVER_URL}  # Valor por defecto si SERVER_URL no está configurado

spring:
  application:
    name: age-detector
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

rapidapi:
  url: ${RAPIDAPI_URL}
  host: ${RAPIDAPI_HOST}
  apikey: ${RAPIDAPI_APIKEY}

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
