# kubectl apply -f juan-condori-00-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: juan-condori-00-secret
  namespace: juan-condori-00-namespace
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLXJvdWdoLWRyZWFtLWE1amd2MDF1LXBvb2xlci51cy1lYXN0LTIuYXdzLm5lb24udGVjaC9zcWw/c3NsbW9kZT1yZXF1aXJl   # en Base64
  DATABASE_USERNAME: ZGJfb3duZXI=   # en Base64
  DATABASE_PASSWORD: Q1R0cVhpNkcyTkZ4   # en Base64
  RAPIDAPI_URL: aHR0cHM6Ly9hZ2UtZGV0ZWN0b3IucC5yYXBpZGFwaS5jb20=   # en Base64
  RAPIDAPI_HOST: YWdlLWRldGVjdG9yLnAucmFwaWRhcGkuY29t   # en Base64
  RAPIDAPI_APIKEY: MzA1NGRjYTI5NG1zaDMxMWZjYzE2ODkzY2U3NHAxN2VmMjRqc25jYmQ4ZWFkNmVkNzY=   # en Base64

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode